### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by yossile** [stickz/rutorrent-rtorrent-build-scripts#3]
I'm trying to run rhis script on a seedbox and it fails with:
```sh
download_list.cc: In member function ‘void core::DownloadList::open_throw(core::Download*)’:
download_list.cc:263:37: error: ‘open_enable_fallocate_all’ is not a member of ‘torrent::Download’
  263 |     openFlags |= torrent::Download::open_enable_fallocate_all;
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:457: download_list.o] Error 1
```
Is it fixable?

**Comment by stickz** [comment]
Could you provide more information about how you are building it? I'm using GCC 14 on the rTorrent GitHub. The build passed.

**Comment by yossile** [comment]
Unfortunately it's a shared one so I don't have much control over GCC.
I just checked and it's version `10.2.1`. I guess that's the reason?

**Comment by stickz** [comment]
If it's a shared seedbox, this could be why. You'll probably have to do a static build. It's probably linking to the wrong version of libtorrent. A static build is much more complex than this script. You'll have to write your own script for that.

**Comment by yossile** [comment]
I guess you are right.
And it's not possible to build for the arch and then upload? Like the qbit binary?
